# Generated by Django 3.2.7 on 2021-10-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
